set(_AMENT_PACKAGE_NAME "yolo26_interfaces")
set(yolo26_interfaces_VERSION "0.0.1")
set(yolo26_interfaces_MAINTAINER "merve <akbeymerve1@gmail.com>")
set(yolo26_interfaces_BUILD_DEPENDS "std_msgs")
set(yolo26_interfaces_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(yolo26_interfaces_BUILD_EXPORT_DEPENDS "std_msgs")
set(yolo26_interfaces_BUILDTOOL_EXPORT_DEPENDS )
set(yolo26_interfaces_EXEC_DEPENDS "rosidl_default_runtime" "std_msgs")
set(yolo26_interfaces_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(yolo26_interfaces_GROUP_DEPENDS )
set(yolo26_interfaces_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(yolo26_interfaces_DEPRECATED "")
set(yolo26_interfaces_EXPORT_TAGS)
list(APPEND yolo26_interfaces_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
